version: 1
update_configs:
    - package_manager: 'javascript'
      directory: '/'
      default_reviewers:
          - 'ponday-dev'
      allowed_updates:
          - match:
              update_type: 'all'
      update_schedule: 'weekly'
      commit_message:
          prefix: 'chore(deps): '

